services:
  - type: web
    name: mypotofolio
    env: php
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader"
    staticPublishPath: public
    routes:
      - type: rewrite
        source: /*
        destination: /index.php